# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
use_frameworks!

target 'ConstrictorTests' do
    pod 'SnapshotTesting'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == "Debug" && defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
                config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
            end
        end
    end
end 
